{
   "webmap":"7b6da68b949b40ae86f95cfac648edd7",
   "bingMapsKey":"",
   "FAI_Email":"",
   "proxyURL":"./resources/proxy.ashx",
   "defaultMenu":"social",
   "showScalebar":true,
   "showSearchBox":true,
   "showShareMenu":true,
   "showSocialMenu":true,
   "showBasemapMenu":true,
   "showLayersMenu":true,
   "showLegendMenu":true,
   "showPlaces":true,
   "showGeolocation":true,
   "alwaysUseProxy":false,
   "aboutPage":"http://www.arcgis.com/home/item.html?id=c74acddfcb1844eb90f8f9d40be2c823",
   "inappSvcURL":"",
   "badWordsURL":"",
   "mailServer":"",
   "pointSymbol":"http://tmimages.esri.com/esri.com/map/bluepoint-21x29.png",
   "locatorURL":"http://tasks.arcgis.com/ArcGIS/rest/services/WorldLocator/GeocodeServer",
   "geometryserviceurl":"http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer",
   "bitly":{
      "login":"",
      "key":"",
      "APIURL":"http://api.bit.ly/v3/shorten"
   },
   "basemaps":{
      "useArcGISOnline":true,
      "title":"ArcGIS Online Basemaps",
      "owner":"esri_en"
   },
   "socialMedia":{
      "socialGeo":{
         "x":"",
         "y":""
      },
      "socialDistance":"regional",
      "popupWidth":"400",
      "popupHeight":"300",
      "clusterImage":"http://tmimages.esri.com/esri.com/map/cluster72x72.png",
      "Ushahidi":{
         "enabled":false,
         "visible":false,
         "uniqueID":"ushahidi",
         "title":"Ushahidi",
         "description":"Incident reports from Ushahidi.",
         "apiURL":"http://de21.digitalasia.chubu.ac.jp/floodmap/api",
         "legendIcon":"http://tmimages.esri.com/esri.com/legend/ushahidi16x16.png",
         "symbol":{
            "url":"http://tmimages.esri.com/esri.com/map/ushahidi25x30.png",
            "width":"18.75",
            "height":"22.5"
         }
      },
      "Flickr":{
         "enabled":true,
         "visible":false,
         "uniqueID":"flickr",
         "key":"fe7e074f8dad46678841c585f38620b7",
         "showSocialSettings":true,
         "title":"Flickr",
         "description":"Photos from Flickr.",
         "legendIcon":"http://tmimages.esri.com/esri.com/map/flickr.png",
         "symbol":{
            "url":"http://tmimages.esri.com/esri.com/map/flickr25x30.png",
            "width":"18.75",
            "height":"22.5"
         },
         "searchTerm":"occupy",
         "flDateFrom":"",
         "flDateTo":""
      },
      "Twitter":{
         "enabled":true,
         "visible":true,
         "uniqueID":"twitter",
         "showSocialSettings":true,
         "title":"Twitter",
         "description":"Tweets from Twitter.",
         "legendIcon":"http://tmimages.esri.com/esri.com/map/twitter-legend-icon-16x16.png",
         "symbol":{
            "url":"http://tmimages.esri.com/esri.com/map/twitter-point-25x30.png",
            "width":"18.75",
            "height":"22.5"
         },
         "searchTerm":"#ows"
      },
      "YouTube":{
         "enabled":true,
         "visible":true,
         "uniqueID":"youtube",
         "showSocialSettings":true,
         "title":"YouTube",
         "description":"Video from YouTube.",
         "legendIcon":"http://tmimages.esri.com/esri.com/map/youtube.png",
         "symbol":{
            "url":"http://tmimages.esri.com/esri.com/map/youtube25x30.png",
            "width":"18.75",
            "height":"22.5"
         },
         "searchTerm":"occupy",
         "YTRange":"this_month"
      }
   }
}